[package]
name = "rust-study"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = {version = "0.7.5", optional=true}
critical-section = "1.2.0"
defmt = "1.0.1"
defmt-rtt = "1.0.0"
embedded-hal = "1.0.0"
panic-halt = "1.0.0"
rp-pico = "0.9.0"
rp2040-boot2 = {version = "0.3.0", optional=true}
rp2040-hal = "0.10.0"

[features]
default = ["boot2", "rt", "critical-section-impl", "rom-func-cache"]
critical-section-impl = ["rp2040-hal/critical-section-impl"]
boot2 = ["rp2040-boot2"]
rt = ["cortex-m-rt","rp2040-hal/rt"]
rp2040-e5 = ["rp2040-hal/rp2040-e5"]
rom-func-cache = ["rp2040-hal/rom-func-cache"]
disable-intrinsics = ["rp2040-hal/disable-intrinsics"]
rom-v2-intrinsics = ["rp2040-hal/rom-v2-intrinsics"]
